api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            #page_parameter_name: _page
            #client_enabled: true
            #enabled_parameter_name: pagination
            items_per_page: 15
            client_items_per_page: true #false by default
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 20
            partial: true
