vich_uploader:
    db_driver: orm

    mappings:
      products:
        uri_prefix: /uploads
        upload_destination: '%kernel.project_dir%/public/uploads'
        # decide how uploaded files would be renamed
        namer: Vich\UploaderBundle\Naming\UniqidNamer
