vich_uploader:
    db_driver: orm

    mappings:
      images:
        uri_prefix: /uploads/images
        upload_destination: '%kernel.project_dir%/public/uploads/images'
        # decide how uploaded files would be renamed
        namer: Vich\UploaderBundle\Naming\UniqidNamer
